// Language switcher for Urban Interiors
const translations = {
    nl: {
        // Navigation
        "nav.diensten": "Diensten",
        "nav.werkwijze": "Werkwijze",
        "nav.realisaties": "Realisaties",
        "nav.over": "Over",
        "nav.contact": "Contact",

        // Footer
        "footer.tagline": "Stijlvolle interieurs op maat, tot in detail. Van ontwerp tot uitvoering met aandacht voor kwaliteit en afwerking.",
        "footer.nav_title": "Navigatie",
        "footer.contact_title": "Contact",
        "footer.phone_label": "Telefoon",
        "footer.email_label": "E-mail",
        "footer.hours_title": "Openingsuren",
        "footer.weekdays": "Maandag - Vrijdag",
        "footer.weekdays_value": "9:00 – 16:00",
        "footer.weekend": "Weekend",
        "footer.weekend_value": "Op afspraak",
        "footer.location_label": "Locatie",
        "footer.location_value": "Europa & Benelux",
        "footer.copyright": "\u00a9 2026 Urban Interiors. Alle rechten voorbehouden.",
        "footer.made_by": "Gemaakt door <a href=\"https://nebula-agency.be\" target=\"_blank\" rel=\"noopener noreferrer\">nebula-agency.be</a>",
        "footer.diensten": "Diensten",
        "footer.werkwijze": "Werkwijze",
        "footer.realisaties": "Realisaties",
        "footer.over": "Over ons",
        "footer.contact": "Contact",

        // Page titles
        "title.home": "Urban Interiors | Interieurs op maat",
        "title.diensten": "Diensten | Urban Interiors",
        "title.werkwijze": "Werkwijze | Urban Interiors",
        "title.realisaties": "Realisaties | Urban Interiors",
        "title.over": "Over ons | Urban Interiors",
        "title.contact": "Contact | Urban Interiors",
        "title.404": "404 | Urban Interiors",

        // Homepage
        "home.hero.label": "Interieur & Renovatie",
        "home.hero.title": "Uw Project. Onze Expertise.<br><em class=\"text-italic\">Perfect Uitgevoerd.</em>",
        "home.hero.subtitle": "Stijlvolle interieurs op maat, tot in detail. Van ontwerp tot uitvoering met aandacht voor kwaliteit en afwerking.",
        "home.hero.cta1": "Bekijk realisaties",
        "home.hero.cta2": "Neem contact op",
        "home.intro.label": "Over ons",
        "home.intro.text": "Wij realiseren totale renovaties, maatwerkinterieurs en uitbreidingen met \u00e9\u00e9n duidelijke missie: kwaliteit leveren zonder compromissen.",
        "home.intro.text2": "Van particuliere woningen tot horeca, winkels en bedrijfsruimtes \u2014 in binnen- \u00e9n buitenland brengen wij projecten tot leven met vakmanschap, precisie en een strakke afwerking.",
        "home.services.label": "Diensten",
        "home.services.title": "Wat wij doen",
        "home.services.s1": "Interieurinrichting",
        "home.services.s2": "Renovatie",
        "home.services.s3": "Totaalproject",
        "home.services.s4": "Keukens",
        "home.services.s5": "Badkamers",
        "home.services.s6": "Schrijnwerk",
        "home.services.cta": "Alle diensten bekijken",
        "home.vision.label": "Onze visie",
        "home.vision.title": "Rust in het ontwerp",
        "home.vision.text1": "Een goed interieur vraagt geen aandacht. Het werkt gewoon. Rust in de ruimte, logica in het ontwerp, kwaliteit in de uitvoering.",
        "home.vision.text2": "Wij geloven dat de beste resultaten ontstaan uit samenwerking. Jij kent je eigen leven het beste. Wij weten hoe we dat vertalen naar ruimte.",
        "home.vision.cta": "Meer over ons",
        "home.portfolio.label": "Portfolio",
        "home.portfolio.title": "Recente realisaties",
        "home.portfolio.p1_title": "Moderne Keuken",
        "home.portfolio.p1_cat": "Keukens",
        "home.portfolio.p2_title": "Mancave",
        "home.portfolio.p2_cat": "Interieur",
        "home.portfolio.p3_title": "Moderne Badkamer",
        "home.portfolio.p3_cat": "Badkamers",
        "home.portfolio.p4_title": "Bar",
        "home.portfolio.p4_cat": "Commercieel",
        "home.portfolio.cta": "Alle projecten bekijken",
        "home.process.label": "Werkwijze",
        "home.process.title": "Een helder traject",
        "home.process.text1": "Van kennismaking tot oplevering in 5 heldere stappen. Je weet altijd wat we doen en wanneer.",
        "home.process.text2": "Geen verrassingen, geen onduidelijkheden. E\u00e9n aanspreekpunt, vaste prijzen en regelmatige updates.",
        "home.process.cta": "Ontdek onze werkwijze",
        "home.cta.title": "Klaar om te starten?",
        "home.cta.text": "Vertel wat je in gedachten hebt. Wij denken mee en maken het concreet.",
        "home.cta.btn": "Neem contact op",

        // Diensten page
        "diensten.header.label": "Wat wij doen",
        "diensten.header.title": "Onze diensten",
        "diensten.header.subtitle": "Van interieurinrichting tot renovatie. Elk project met dezelfde aandacht voor detail.",
        "diensten.s1.title": "Interieurinrichting",
        "diensten.s1.desc": "Vanuit jouw wensen maken we een concreet plan voor indeling, materiaal en maatkasten.",
        "diensten.s2.title": "Renovatie",
        "diensten.s2.desc": "Wij co\u00f6rdineren de werken, bewaken de planning en zorgen voor technische opvolging.",
        "diensten.s3.title": "Totaalproject",
        "diensten.s3.desc": "Van ontwerp tot de laatste afwerking. Sleutel op de deur, klaar om te wonen.",
        "diensten.s4.title": "Keukens",
        "diensten.s4.desc": "Functionele keukens met oog voor detail, ergonomie en kwaliteitsmaterialen.",
        "diensten.s5.title": "Badkamers",
        "diensten.s5.desc": "Badkamers met aandacht voor sfeer, functionaliteit en duurzaamheid.",
        "diensten.s6.title": "Schrijnwerk",
        "diensten.s6.desc": "Maatkasten, deuren en trappen. Vakmanschap in hout.",
        "diensten.split.label": "Voor wie",
        "diensten.split.title": "Particulieren & bedrijven",
        "diensten.split.text": "We werken voor wie waarde hecht aan kwaliteit. Die liever iets goed doet dan iets snel.",
        "diensten.split.cta": "Neem contact op",
        "diensten.cta.title": "Een project in gedachten?",
        "diensten.cta.text": "Vertel ons waar je aan denkt. We luisteren en denken vrijblijvend mee.",
        "diensten.cta.btn": "Neem contact op",

        // Dienst: Interieurinrichting
        "title.d_interieur": "Interieurinrichting | Urban Interiors",
        "d_interieur.hero.label": "Dienst 01 — Interieurinrichting",
        "d_interieur.hero.title": "Interieurinrichting<br><em class=\"text-italic\">op maat van jouw leven</em>",
        "d_interieur.hero.subtitle": "Van indeling en materiaalkeuze tot maatkasten. Wij vertalen jouw manier van wonen naar een interieur dat klopt, rustig en afgewerkt tot in het detail.",
        "d_interieur.hero.cta1": "Plan een gesprek",
        "d_interieur.hero.cta2": "Bekijk realisaties",
        "d_interieur.aanpak.label": "Onze aanpak",
        "d_interieur.aanpak.title": "Van wens naar ruimte",
        "d_interieur.aanpak.text": "Een goed interieur begint bij luisteren. We brengen jouw wensen, je ruimte en je budget samen in één helder plan, en voeren het uit zonder verrassingen.",
        "d_interieur.aanpak.b1": "✔ Persoonlijk ontwerp- en indelingsplan",
        "d_interieur.aanpak.b2": "✔ Advies in materialen, kleuren en verlichting",
        "d_interieur.aanpak.b3": "✔ Maatkasten en geïntegreerde oplossingen",
        "d_interieur.aanpak.b4": "✔ Één aanspreekpunt van ontwerp tot oplevering",
        "d_interieur.aanpak.text2": "Zo ontstaat een interieur dat niet alleen mooi is, maar ook werkt, dag na dag.",
        "d_interieur.real.label": "Realisaties",
        "d_interieur.real.title": "Interieurs die we realiseerden",
        "d_interieur.real.p1_title": "Woonkamer Inrichting",
        "d_interieur.real.p1_cat": "Interieur",
        "d_interieur.real.p2_title": "Mancave",
        "d_interieur.real.p2_cat": "Interieur",
        "d_interieur.real.p3_title": "Kantoor Inrichting",
        "d_interieur.real.p3_cat": "Commercieel",
        "d_interieur.real.p4_title": "Maatwerk Bar",
        "d_interieur.real.p4_cat": "Interieur",
        "d_interieur.real.cta": "Alle realisaties bekijken",
        "d_interieur.cta.title": "Klaar voor jouw interieur?",
        "d_interieur.cta.text": "Vertel ons waar je aan denkt. We luisteren en denken vrijblijvend mee.",
        "d_interieur.cta.btn": "Neem contact op",
        // diensten-renovatie
        "title.d_renovatie": "Renovatie | Urban Interiors",
        "d_renovatie.hero.label": "Dienst 02 — Renovatie",
        "d_renovatie.hero.title": "Renoveren<br><em class=\"text-italic\">zonder zorgen</em>",
        "d_renovatie.hero.subtitle": "Wij nemen je renovatie volledig in handen. Eén aanspreekpunt, een strakke planning en technische opvolging, van afbraak tot oplevering.",
        "d_renovatie.hero.cta1": "Plan een gesprek",
        "d_renovatie.hero.cta2": "Bekijk realisaties",
        "d_renovatie.aanpak.label": "Onze aanpak",
        "d_renovatie.aanpak.title": "Volledige coördinatie van A tot Z",
        "d_renovatie.aanpak.text": "Renoveren vraagt visie, planning en vakkennis. Wij coördineren alle werken, bewaken planning én budget en houden je op elk moment op de hoogte.",
        "d_renovatie.aanpak.b1": "✔ Eén vast aanspreekpunt",
        "d_renovatie.aanpak.b2": "✔ Volledige coördinatie van de werken",
        "d_renovatie.aanpak.b3": "✔ Technische opvolging en kwaliteitscontrole",
        "d_renovatie.aanpak.b4": "✔ Respect voor planning én budget",
        "d_renovatie.aanpak.text2": "Jij hoeft je nergens zorgen over te maken, wij zorgen voor een vlotte uitvoering en een perfect eindresultaat.",
        "d_renovatie.real.label": "Realisaties",
        "d_renovatie.real.title": "Renovaties die we realiseerden",
        "d_renovatie.real.p1_title": "Renovatieproject",
        "d_renovatie.real.p1_cat": "Renovatie",
        "d_renovatie.real.p2_title": "Buitenstructuur",
        "d_renovatie.real.p2_cat": "Buitenwerk",
        "d_renovatie.real.p3_title": "Kapsalon",
        "d_renovatie.real.p3_cat": "Commercieel",
        "d_renovatie.real.p4_title": "Maatwerk Afwerking",
        "d_renovatie.real.p4_cat": "Maatwerk",
        "d_renovatie.real.cta": "Alle realisaties bekijken",
        "d_renovatie.cta.title": "Renovatieplannen?",
        "d_renovatie.cta.text": "Vertel ons over je project. We denken vrijblijvend met je mee.",
        "d_renovatie.cta.btn": "Neem contact op",
        // diensten-totaalproject
        "title.d_totaal": "Totaalproject | Urban Interiors",
        "d_totaal.hero.label": "Dienst 03 — Totaalproject",
        "d_totaal.hero.title": "Sleutel op de deur,<br><em class=\"text-italic\">klaar om te wonen</em>",
        "d_totaal.hero.subtitle": "Van eerste ontwerp tot de laatste afwerking. Wij realiseren je volledige project, zodat jij enkel nog de deur hoeft open te doen.",
        "d_totaal.hero.cta1": "Plan een gesprek",
        "d_totaal.hero.cta2": "Bekijk realisaties",
        "d_totaal.aanpak.label": "Onze aanpak",
        "d_totaal.aanpak.title": "Van ontwerp tot oplevering",
        "d_totaal.aanpak.text": "Eén partner voor je hele project. We tekenen, plannen, coördineren en werken af, met dezelfde aandacht voor elk detail.",
        "d_totaal.aanpak.b1": "✔ Ontwerp en 3D-visualisatie",
        "d_totaal.aanpak.b2": "✔ Volledige coördinatie van alle vakmensen",
        "d_totaal.aanpak.b3": "✔ Maatwerk en afwerking in eigen beheer",
        "d_totaal.aanpak.b4": "✔ Sleutel-op-de-deur oplevering",
        "d_totaal.aanpak.text2": "Eén aanspreekpunt, één planning, één eindverantwoordelijke, voor een resultaat dat volledig klopt.",
        "d_totaal.real.label": "Realisaties",
        "d_totaal.real.title": "Totaalprojecten die we realiseerden",
        "d_totaal.real.p1_title": "Strakke Keuken",
        "d_totaal.real.p1_cat": "Keukens",
        "d_totaal.real.p2_title": "Woonkamer",
        "d_totaal.real.p2_cat": "Interieur",
        "d_totaal.real.p3_title": "Moderne Badkamer",
        "d_totaal.real.p3_cat": "Badkamers",
        "d_totaal.real.p4_title": "Maatkast",
        "d_totaal.real.p4_cat": "Maatkasten",
        "d_totaal.real.cta": "Alle realisaties bekijken",
        "d_totaal.cta.title": "Een volledig project in gedachten?",
        "d_totaal.cta.text": "Vertel ons je plannen. We maken het samen concreet.",
        "d_totaal.cta.btn": "Neem contact op",
        // diensten-keukens
        "title.d_keukens": "Keukens op maat | Urban Interiors",
        "d_keukens.hero.label": "Dienst 04 — Keukens",
        "d_keukens.hero.title": "Keukens<br><em class=\"text-italic\">om in te leven</em>",
        "d_keukens.hero.subtitle": "Functionele keukens op maat, met oog voor ergonomie, detail en duurzame materialen. Het kloppend hart van je woning.",
        "d_keukens.hero.cta1": "Plan een gesprek",
        "d_keukens.hero.cta2": "Bekijk realisaties",
        "d_keukens.aanpak.label": "Onze aanpak",
        "d_keukens.aanpak.title": "Doordacht tot in elk detail",
        "d_keukens.aanpak.text": "Een keuken moet werken zoals jij kookt en leeft. We vertrekken vanuit jouw gewoontes en vertalen die naar een ergonomisch, tijdloos ontwerp.",
        "d_keukens.aanpak.b1": "✔ Ergonomisch ontwerp op maat",
        "d_keukens.aanpak.b2": "✔ Hoogwaardige werkbladen en materialen",
        "d_keukens.aanpak.b3": "✔ Geïntegreerde toestellen en verlichting",
        "d_keukens.aanpak.b4": "✔ Strakke, naadloze afwerking",
        "d_keukens.aanpak.text2": "Van klassiek warm tot strak en zwart, we bouwen de keuken die bij jou past.",
        "d_keukens.real.label": "Realisaties",
        "d_keukens.real.title": "Keukens die we realiseerden",
        "d_keukens.real.p1_title": "Strakke Keuken",
        "d_keukens.real.p1_cat": "Keukens",
        "d_keukens.real.p2_title": "Design Keuken",
        "d_keukens.real.p2_cat": "Keukens",
        "d_keukens.real.p3_title": "Zwarte Keuken",
        "d_keukens.real.p3_cat": "Keukens",
        "d_keukens.real.p4_title": "Moderne Keuken",
        "d_keukens.real.p4_cat": "Keukens",
        "d_keukens.real.cta": "Alle realisaties bekijken",
        "d_keukens.cta.title": "Droom je van een nieuwe keuken?",
        "d_keukens.cta.text": "Vertel ons je wensen. We denken vrijblijvend mee.",
        "d_keukens.cta.btn": "Neem contact op",
        // diensten-badkamers
        "title.d_badkamers": "Badkamers op maat | Urban Interiors",
        "d_badkamers.hero.label": "Dienst 05 — Badkamers",
        "d_badkamers.hero.title": "Badkamers<br><em class=\"text-italic\">met rust en sfeer</em>",
        "d_badkamers.hero.subtitle": "Een badkamer met aandacht voor sfeer, functionaliteit en duurzaamheid. Jouw plek om de dag te beginnen en af te sluiten.",
        "d_badkamers.hero.cta1": "Plan een gesprek",
        "d_badkamers.hero.cta2": "Bekijk realisaties",
        "d_badkamers.aanpak.label": "Onze aanpak",
        "d_badkamers.aanpak.title": "Sfeer, functie en duurzaamheid",
        "d_badkamers.aanpak.text": "We ontwerpen je badkamer rond comfort en beleving, met materialen die bestand zijn tegen vocht en tijd.",
        "d_badkamers.aanpak.b1": "✔ Indeling afgestemd op je ruimte",
        "d_badkamers.aanpak.b2": "✔ Vochtbestendige, duurzame materialen",
        "d_badkamers.aanpak.b3": "✔ Sfeervolle verlichting en maatmeubel",
        "d_badkamers.aanpak.b4": "✔ Strakke, onderhoudsvriendelijke afwerking",
        "d_badkamers.aanpak.text2": "Van compacte gastenbadkamer tot ruime wellness, alles tot in detail uitgewerkt.",
        "d_badkamers.real.label": "Realisaties",
        "d_badkamers.real.title": "Badkamers en afwerking",
        "d_badkamers.real.p1_title": "Moderne Badkamer",
        "d_badkamers.real.p1_cat": "Badkamers",
        "d_badkamers.real.p2_title": "Maatwerk Afwerking",
        "d_badkamers.real.p2_cat": "Maatwerk",
        "d_badkamers.real.p3_title": "Interieurdetail",
        "d_badkamers.real.p3_cat": "Interieur",
        "d_badkamers.real.p4_title": "Woonruimte",
        "d_badkamers.real.p4_cat": "Interieur",
        "d_badkamers.real.cta": "Alle realisaties bekijken",
        "d_badkamers.cta.title": "Toe aan een nieuwe badkamer?",
        "d_badkamers.cta.text": "Vertel ons je wensen. We denken vrijblijvend mee.",
        "d_badkamers.cta.btn": "Neem contact op",
        // diensten-schrijnwerk
        "title.d_schrijnwerk": "Schrijnwerk op maat | Urban Interiors",
        "d_schrijnwerk.hero.label": "Dienst 06 — Schrijnwerk",
        "d_schrijnwerk.hero.title": "Schrijnwerk<br><em class=\"text-italic\">vakmanschap in hout</em>",
        "d_schrijnwerk.hero.subtitle": "Maatkasten, deuren en trappen, op maat gemaakt en perfect afgewerkt. Geïntegreerde oplossingen die een ruimte compleet maken.",
        "d_schrijnwerk.hero.cta1": "Plan een gesprek",
        "d_schrijnwerk.hero.cta2": "Bekijk realisaties",
        "d_schrijnwerk.aanpak.label": "Onze aanpak",
        "d_schrijnwerk.aanpak.title": "Maatwerk tot op de millimeter",
        "d_schrijnwerk.aanpak.text": "Elk stuk schrijnwerk wordt op maat ontworpen en met zorg uitgevoerd, in materialen die jaren meegaan.",
        "d_schrijnwerk.aanpak.b1": "✔ Maatkasten en dressings",
        "d_schrijnwerk.aanpak.b2": "✔ Binnendeuren en trappen op maat",
        "d_schrijnwerk.aanpak.b3": "✔ Geïntegreerde, naadloze oplossingen",
        "d_schrijnwerk.aanpak.b4": "✔ Duurzame materialen en strakke afwerking",
        "d_schrijnwerk.aanpak.text2": "Van een onzichtbare inbouwkast tot een markante trap, alles met dezelfde precisie.",
        "d_schrijnwerk.real.label": "Realisaties",
        "d_schrijnwerk.real.title": "Schrijnwerk dat we realiseerden",
        "d_schrijnwerk.real.p1_title": "Multiplex Maatkast",
        "d_schrijnwerk.real.p1_cat": "Maatkasten",
        "d_schrijnwerk.real.p2_title": "Maatkast Detail",
        "d_schrijnwerk.real.p2_cat": "Maatkasten",
        "d_schrijnwerk.real.p3_title": "Zolder Maatkast",
        "d_schrijnwerk.real.p3_cat": "Maatkasten",
        "d_schrijnwerk.real.p4_title": "Maatwerk Bar",
        "d_schrijnwerk.real.p4_cat": "Maatkasten",
        "d_schrijnwerk.real.cta": "Alle realisaties bekijken",
        "d_schrijnwerk.cta.title": "Een idee voor maatwerk?",
        "d_schrijnwerk.cta.text": "Vertel ons je wensen. We denken vrijblijvend mee.",
        "d_schrijnwerk.cta.btn": "Neem contact op",

        // Werkwijze page
        "werkwijze.header.label": "Van idee tot realisatie",
        "werkwijze.header.title": "Werkwijze",
        "werkwijze.header.subtitle": "Een helder traject in vijf stappen. Geen verrassingen, wel een resultaat dat blijft.",
        "werkwijze.step1.title": "Kennismaking",
        "werkwijze.step1.desc": "Een vrijblijvend gesprek bij jou thuis. We luisteren naar wat je wilt en wat je mist.",
        "werkwijze.step2.title": "Concept & plan",
        "werkwijze.step2.desc": "We vertalen het gesprek naar een visueel voorstel. Ruimte voor feedback is altijd inbegrepen.",
        "werkwijze.step3.title": "Materialen & offerte",
        "werkwijze.step3.desc": "Showroombezoeken, stalen en een transparante begroting. Jij beslist, wij adviseren.",
        "werkwijze.step4.title": "Uitvoering",
        "werkwijze.step4.desc": "Wij co\u00f6rdineren alles. E\u00e9n aanspreekpunt, regelmatige updates, geen zorgen.",
        "werkwijze.step5.title": "Oplevering",
        "werkwijze.step5.desc": "Klaar als alles klopt. We blijven bereikbaar na de sleuteloverdracht.",
        "werkwijze.g1.title": "Vaste prijs",
        "werkwijze.g1.desc": "Na goedkeuring van de offerte verandert de prijs niet. Geen verrassingen achteraf, geen verstopte meerkosten. Wat we afspreken, dat is wat je betaalt.",
        "werkwijze.g2.title": "E\u00e9n aanspreekpunt",
        "werkwijze.g2.desc": "Je werkt altijd met dezelfde persoon. E\u00e9n contactpersoon die het volledige project overziet \u2014 van eerste schets tot de laatste afwerking.",
        "werkwijze.g3.title": "Heldere planning",
        "werkwijze.g3.desc": "Je weet vooraf wanneer elke fase start en eindigt. Geen giswerk, geen wachten in het ongewisse. Regelmatige updates houden je bij elke stap betrokken.",
        "werkwijze.cta.title": "Klaar voor een eerste gesprek?",
        "werkwijze.cta.text": "Vertel ons over jouw project. We plannen vrijblijvend een kennismaking.",
        "werkwijze.cta.btn1": "Neem contact op",
        "werkwijze.cta.btn2": "Bekijk realisaties",

        // Realisaties page
        "realisaties.header.label": "Portfolio",
        "realisaties.header.title": "Realisaties",
        "realisaties.header.subtitle": "Een selectie van afgeronde projecten. Verschillende woningen, verschillende stijlen. E\u00e9n constante: aandacht voor afwerking.",
        "realisaties.filter.all": "Alles",
        "realisaties.filter.keukens": "Keukens",
        "realisaties.filter.badkamers": "Badkamers",
        "realisaties.filter.maatkasten": "Maatkasten",
        "realisaties.filter.woonkamer": "Woonkamer",
        "realisaties.filter.commercieel": "Commercieel",
        "realisaties.filter.buitenwerk": "Buitenwerk",
        "realisaties.stat.projects": "Projecten voltooid",
        "realisaties.stat.years": "Jaar ervaring",
        "realisaties.stat.clients": "Tevreden klanten",
        "realisaties.stat.region": "Europa & Benelux",
        "realisaties.cta.title": "Jouw project in deze lijst?",
        "realisaties.cta.text": "Vertel ons waar je aan denkt. We bespreken vrijblijvend de mogelijkheden.",
        "realisaties.cta.btn1": "Neem contact op",
        "realisaties.cta.btn2": "Onze diensten",

        // Over page
        "over.header.label": "Wie wij zijn",
        "over.header.title": "Over Urban Interiors",
        "over.header.subtitle": "Rust in de ruimte, logica in het ontwerp, kwaliteit in de uitvoering.",
        "over.vision.label": "Onze visie",
        "over.vision.title": "Rust in het ontwerp",
        "over.vision.text1": "Urban Interiors ontstond vanuit een eenvoudige overtuiging: een interieur moet logisch werken \u00e9n mooi zijn.",
        "over.vision.text2": "We zoeken de balans. Dat vraagt om aandacht. Voor hoe je woont, beweegt, leeft. Voor materialen die ouder worden met gratie.",
        "over.stat.projects": "Projecten",
        "over.stat.years": "Jaar ervaring",
        "over.stat.clients": "Tevreden klanten",
        "over.stat.region": "Europa & Benelux",
        "over.why.label": "Waarom wij",
        "over.why.title": "Jong en dynamisch",
        "over.why.text1": "Een jong, dynamisch bedrijf met uitgebreide ervaring in de bouwsector.",
        "over.why.text2": "We combineren frisse idee\u00ebn met bewezen vakmanschap. Persoonlijke aandacht met professionele uitvoering.",
        "over.cta.title": "Zin om kennis te maken?",
        "over.cta.text": "We vertellen graag meer over onze aanpak. Vrijblijvend.",
        "over.cta.btn1": "Neem contact op",
        "over.cta.btn2": "Bekijk realisaties",

        // Contact page
        "contact.header.label": "Laten we praten",
        "contact.header.title": "Contact",
        "contact.header.subtitle": "Vertel ons over jouw project. We luisteren en denken vrijblijvend mee.",
        "contact.form.title": "Stuur een bericht",
        "contact.form.name": "Naam",
        "contact.form.name_ph": "Je naam",
        "contact.form.email": "E-mailadres",
        "contact.form.email_ph": "naam@voorbeeld.be",
        "contact.form.phone": "Telefoon",
        "contact.form.phone_ph": "+32 ...",
        "contact.form.message": "Bericht",
        "contact.form.message_ph": "Vertel kort over je project...",
        "contact.form.submit": "Verstuur bericht",
        "contact.form.success": "Bedankt voor je bericht! We nemen snel contact op.",
        "contact.info.title": "Contactgegevens",
        "contact.info.phone_label": "Telefoon",
        "contact.info.email_label": "E-mail",
        "contact.info.location_label": "Locatie",
        "contact.info.location_value": "Europa & Benelux",
        "contact.info.hours_label": "Openingsuren",
        "contact.info.hours_value": "Ma \u2013 Vr: 9:00 \u2013 16:00",

        // Bedankt page
        "bedankt.label": "Bericht verzonden",
        "bedankt.title": "Bedankt voor uw bericht",
        "bedankt.text": "Wij hebben uw bericht goed ontvangen en nemen zo snel mogelijk contact met u op.",
        "bedankt.cta": "Terug naar home",

        // 404 page
        "error.label": "Foutmelding",
        "error.title": "Pagina niet gevonden",
        "error.subtitle": "De pagina die je zoekt bestaat niet of is verplaatst.",
        "error.text": "Geen zorgen, we brengen je terug op het juiste pad. Bekijk onze diensten of neem contact met ons op.",
        "error.btn_home": "Naar de homepagina",
        "error.btn_contact": "Neem contact op",
        "error.cta.title": "Op zoek naar iets?",
        "error.cta.text": "Ontdek onze diensten of bekijk onze realisaties.",
        "error.cta.btn1": "Onze diensten",
        "error.cta.btn2": "Bekijk realisaties"
    },

    fr: {
        // Navigation
        "nav.diensten": "Services",
        "nav.werkwijze": "Approche",
        "nav.realisaties": "R\u00e9alisations",
        "nav.over": "\u00c0 propos",
        "nav.contact": "Contact",

        // Footer
        "footer.tagline": "Des int\u00e9rieurs \u00e9l\u00e9gants sur mesure, dans les moindres d\u00e9tails. De la conception \u00e0 la r\u00e9alisation avec attention pour la qualit\u00e9 et les finitions.",
        "footer.nav_title": "Navigation",
        "footer.contact_title": "Contact",
        "footer.phone_label": "T\u00e9l\u00e9phone",
        "footer.email_label": "E-mail",
        "footer.hours_title": "Heures d'ouverture",
        "footer.weekdays": "Lundi - Vendredi",
        "footer.weekdays_value": "9h00 \u2013 16h00",
        "footer.weekend": "Weekend",
        "footer.weekend_value": "Sur rendez-vous",
        "footer.location_label": "Localisation",
        "footer.location_value": "Europe & Benelux",
        "footer.copyright": "\u00a9 2026 Urban Interiors. Tous droits r\u00e9serv\u00e9s.",
        "footer.made_by": "Cr\u00e9\u00e9 par <a href=\"https://nebula-agency.be\" target=\"_blank\" rel=\"noopener noreferrer\">nebula-agency.be</a>",
        "footer.diensten": "Services",
        "footer.werkwijze": "Approche",
        "footer.realisaties": "R\u00e9alisations",
        "footer.over": "\u00c0 propos",
        "footer.contact": "Contact",

        // Page titles
        "title.home": "Urban Interiors | Int\u00e9rieurs sur mesure",
        "title.diensten": "Services | Urban Interiors",
        "title.werkwijze": "Approche | Urban Interiors",
        "title.realisaties": "R\u00e9alisations | Urban Interiors",
        "title.over": "\u00c0 propos | Urban Interiors",
        "title.contact": "Contact | Urban Interiors",
        "title.404": "404 | Urban Interiors",

        // Homepage
        "home.hero.label": "Int\u00e9rieur & R\u00e9novation",
        "home.hero.title": "Votre Projet. Notre Expertise.<br><em class=\"text-italic\">Parfaitement R\u00e9alis\u00e9.</em>",
        "home.hero.subtitle": "Des int\u00e9rieurs \u00e9l\u00e9gants sur mesure, dans les moindres d\u00e9tails. De la conception \u00e0 la r\u00e9alisation avec attention pour la qualit\u00e9.",
        "home.hero.cta1": "Voir les r\u00e9alisations",
        "home.hero.cta2": "Nous contacter",
        "home.intro.label": "\u00c0 propos",
        "home.intro.text": "Nous r\u00e9alisons des r\u00e9novations compl\u00e8tes, des int\u00e9rieurs sur mesure et des extensions avec une mission claire : livrer la qualit\u00e9 sans compromis.",
        "home.intro.text2": "Des maisons priv\u00e9es \u00e0 l'horeca, magasins et espaces professionnels \u2014 en Belgique et \u00e0 l'\u00e9tranger, nous donnons vie \u00e0 vos projets avec savoir-faire, pr\u00e9cision et une finition impeccable.",
        "home.services.label": "Services",
        "home.services.title": "Ce que nous faisons",
        "home.services.s1": "Am\u00e9nagement int\u00e9rieur",
        "home.services.s2": "R\u00e9novation",
        "home.services.s3": "Projet cl\u00e9 en main",
        "home.services.s4": "Cuisines",
        "home.services.s5": "Salles de bain",
        "home.services.s6": "Menuiserie",
        "home.services.cta": "Tous nos services",
        "home.vision.label": "Notre vision",
        "home.vision.title": "Le calme dans le design",
        "home.vision.text1": "Un bon int\u00e9rieur ne demande pas d'attention. Il fonctionne simplement. Le calme dans l'espace, la logique dans la conception, la qualit\u00e9 dans l'ex\u00e9cution.",
        "home.vision.text2": "Nous croyons que les meilleurs r\u00e9sultats naissent de la collaboration. Vous connaissez votre vie mieux que quiconque. Nous savons comment la traduire en espace.",
        "home.vision.cta": "En savoir plus",
        "home.portfolio.label": "Portfolio",
        "home.portfolio.title": "R\u00e9alisations r\u00e9centes",
        "home.portfolio.p1_title": "Cuisine Moderne",
        "home.portfolio.p1_cat": "Cuisines",
        "home.portfolio.p2_title": "Mancave",
        "home.portfolio.p2_cat": "Int\u00e9rieur",
        "home.portfolio.p3_title": "Salle de Bain Moderne",
        "home.portfolio.p3_cat": "Salles de bain",
        "home.portfolio.p4_title": "Bar",
        "home.portfolio.p4_cat": "Commercial",
        "home.portfolio.cta": "Tous les projets",
        "home.process.label": "Approche",
        "home.process.title": "Un parcours clair",
        "home.process.text1": "De la premi\u00e8re rencontre \u00e0 la livraison en 5 \u00e9tapes claires. Vous savez toujours ce que nous faisons et quand.",
        "home.process.text2": "Pas de surprises, pas d'ambigu\u00eft\u00e9s. Un seul interlocuteur, des prix fixes et des mises \u00e0 jour r\u00e9guli\u00e8res.",
        "home.process.cta": "D\u00e9couvrir notre approche",
        "home.cta.title": "Pr\u00eat \u00e0 commencer ?",
        "home.cta.text": "Dites-nous ce que vous avez en t\u00eate. Nous r\u00e9fl\u00e9chissons avec vous et le concr\u00e9tisons.",
        "home.cta.btn": "Nous contacter",

        // Diensten page
        "diensten.header.label": "Ce que nous faisons",
        "diensten.header.title": "Nos services",
        "diensten.header.subtitle": "De l'am\u00e9nagement int\u00e9rieur \u00e0 la r\u00e9novation. Chaque projet avec la m\u00eame attention aux d\u00e9tails.",
        "diensten.s1.title": "Am\u00e9nagement int\u00e9rieur",
        "diensten.s1.desc": "\u00c0 partir de vos souhaits, nous \u00e9laborons un plan concret pour l'agencement, les mat\u00e9riaux et les rangements sur mesure.",
        "diensten.s2.title": "R\u00e9novation",
        "diensten.s2.desc": "Nous coordonnons les travaux, surveillons le planning et assurons le suivi technique.",
        "diensten.s3.title": "Projet cl\u00e9 en main",
        "diensten.s3.desc": "De la conception \u00e0 la derni\u00e8re finition. Cl\u00e9 sur porte, pr\u00eat \u00e0 vivre.",
        "diensten.s4.title": "Cuisines",
        "diensten.s4.desc": "Des cuisines fonctionnelles avec attention aux d\u00e9tails, \u00e0 l'ergonomie et aux mat\u00e9riaux de qualit\u00e9.",
        "diensten.s5.title": "Salles de bain",
        "diensten.s5.desc": "Des salles de bain avec attention pour l'ambiance, la fonctionnalit\u00e9 et la durabilit\u00e9.",
        "diensten.s6.title": "Menuiserie",
        "diensten.s6.desc": "Armoires sur mesure, portes et escaliers. L'artisanat du bois.",
        "diensten.split.label": "Pour qui",
        "diensten.split.title": "Particuliers & entreprises",
        "diensten.split.text": "Nous travaillons pour ceux qui valorisent la qualit\u00e9. Ceux qui pr\u00e9f\u00e8rent bien faire plut\u00f4t que vite faire.",
        "diensten.split.cta": "Nous contacter",
        "diensten.cta.title": "Un projet en t\u00eate ?",
        "diensten.cta.text": "Dites-nous \u00e0 quoi vous pensez. Nous \u00e9coutons et r\u00e9fl\u00e9chissons avec vous, sans engagement.",
        "diensten.cta.btn": "Nous contacter",

        // Service : Aménagement d'intérieur
        "title.d_interieur": "Aménagement d'intérieur | Urban Interiors",
        "d_interieur.hero.label": "Service 01 — Aménagement d'intérieur",
        "d_interieur.hero.title": "Aménagement d'intérieur<br><em class=\"text-italic\">à la mesure de votre vie</em>",
        "d_interieur.hero.subtitle": "De l'agencement et du choix des matériaux jusqu'aux armoires sur mesure. Nous traduisons votre façon de vivre en un intérieur juste, apaisé et fini dans le moindre détail.",
        "d_interieur.hero.cta1": "Planifier un entretien",
        "d_interieur.hero.cta2": "Voir les réalisations",
        "d_interieur.aanpak.label": "Notre approche",
        "d_interieur.aanpak.title": "Du souhait à l'espace",
        "d_interieur.aanpak.text": "Un bon intérieur commence par l'écoute. Nous réunissons vos souhaits, votre espace et votre budget dans un plan clair, et le réalisons sans surprises.",
        "d_interieur.aanpak.b1": "✔ Plan de conception et d'agencement personnalisé",
        "d_interieur.aanpak.b2": "✔ Conseils en matériaux, couleurs et éclairage",
        "d_interieur.aanpak.b3": "✔ Armoires sur mesure et solutions intégrées",
        "d_interieur.aanpak.b4": "✔ Un seul interlocuteur, de la conception à la livraison",
        "d_interieur.aanpak.text2": "Ainsi naît un intérieur qui n'est pas seulement beau, mais qui fonctionne, jour après jour.",
        "d_interieur.real.label": "Réalisations",
        "d_interieur.real.title": "Des intérieurs que nous avons réalisés",
        "d_interieur.real.p1_title": "Aménagement de séjour",
        "d_interieur.real.p1_cat": "Intérieur",
        "d_interieur.real.p2_title": "Mancave",
        "d_interieur.real.p2_cat": "Intérieur",
        "d_interieur.real.p3_title": "Aménagement de bureau",
        "d_interieur.real.p3_cat": "Commercial",
        "d_interieur.real.p4_title": "Bar sur mesure",
        "d_interieur.real.p4_cat": "Intérieur",
        "d_interieur.real.cta": "Voir toutes les réalisations",
        "d_interieur.cta.title": "Prêt pour votre intérieur ?",
        "d_interieur.cta.text": "Dites-nous à quoi vous pensez. Nous écoutons et réfléchissons avec vous, sans engagement.",
        "d_interieur.cta.btn": "Nous contacter",
        // diensten-renovatie
        "title.d_renovatie": "Rénovation | Urban Interiors",
        "d_renovatie.hero.label": "Service 02 — Rénovation",
        "d_renovatie.hero.title": "Rénover<br><em class=\"text-italic\">en toute sérénité</em>",
        "d_renovatie.hero.subtitle": "Nous prenons votre rénovation entièrement en main. Un seul interlocuteur, un planning rigoureux et un suivi technique, de la démolition à la livraison.",
        "d_renovatie.hero.cta1": "Planifier un entretien",
        "d_renovatie.hero.cta2": "Voir les réalisations",
        "d_renovatie.aanpak.label": "Notre approche",
        "d_renovatie.aanpak.title": "Une coordination complète de A à Z",
        "d_renovatie.aanpak.text": "Rénover demande de la vision, de la planification et du savoir-faire. Nous coordonnons tous les travaux, surveillons le planning et le budget, et vous tenons informé à chaque étape.",
        "d_renovatie.aanpak.b1": "✔ Un seul interlocuteur fixe",
        "d_renovatie.aanpak.b2": "✔ Coordination complète des travaux",
        "d_renovatie.aanpak.b3": "✔ Suivi technique et contrôle qualité",
        "d_renovatie.aanpak.b4": "✔ Respect du planning et du budget",
        "d_renovatie.aanpak.text2": "Vous n'avez à vous soucier de rien : nous assurons une exécution fluide et un résultat impeccable.",
        "d_renovatie.real.label": "Réalisations",
        "d_renovatie.real.title": "Des rénovations que nous avons réalisées",
        "d_renovatie.real.p1_title": "Projet de rénovation",
        "d_renovatie.real.p1_cat": "Rénovation",
        "d_renovatie.real.p2_title": "Structure extérieure",
        "d_renovatie.real.p2_cat": "Extérieur",
        "d_renovatie.real.p3_title": "Salon de coiffure",
        "d_renovatie.real.p3_cat": "Commercial",
        "d_renovatie.real.p4_title": "Finition sur mesure",
        "d_renovatie.real.p4_cat": "Sur mesure",
        "d_renovatie.real.cta": "Voir toutes les réalisations",
        "d_renovatie.cta.title": "Des projets de rénovation ?",
        "d_renovatie.cta.text": "Parlez-nous de votre projet. Nous réfléchissons avec vous, sans engagement.",
        "d_renovatie.cta.btn": "Nous contacter",
        // diensten-totaalproject
        "title.d_totaal": "Projet clé en main | Urban Interiors",
        "d_totaal.hero.label": "Service 03 — Projet clé en main",
        "d_totaal.hero.title": "Clé en main,<br><em class=\"text-italic\">prêt à vivre</em>",
        "d_totaal.hero.subtitle": "Du premier croquis à la dernière finition. Nous réalisons l'intégralité de votre projet, il ne vous reste qu'à ouvrir la porte.",
        "d_totaal.hero.cta1": "Planifier un entretien",
        "d_totaal.hero.cta2": "Voir les réalisations",
        "d_totaal.aanpak.label": "Notre approche",
        "d_totaal.aanpak.title": "De la conception à la livraison",
        "d_totaal.aanpak.text": "Un seul partenaire pour tout votre projet. Nous dessinons, planifions, coordonnons et finissons, avec la même attention pour chaque détail.",
        "d_totaal.aanpak.b1": "✔ Conception et visualisation 3D",
        "d_totaal.aanpak.b2": "✔ Coordination complète de tous les corps de métier",
        "d_totaal.aanpak.b3": "✔ Sur mesure et finition en gestion propre",
        "d_totaal.aanpak.b4": "✔ Livraison clé en main",
        "d_totaal.aanpak.text2": "Un seul interlocuteur, un seul planning, un seul responsable, pour un résultat parfaitement maîtrisé.",
        "d_totaal.real.label": "Réalisations",
        "d_totaal.real.title": "Des projets clé en main que nous avons réalisés",
        "d_totaal.real.p1_title": "Cuisine épurée",
        "d_totaal.real.p1_cat": "Cuisines",
        "d_totaal.real.p2_title": "Séjour",
        "d_totaal.real.p2_cat": "Intérieur",
        "d_totaal.real.p3_title": "Salle de bain moderne",
        "d_totaal.real.p3_cat": "Salles de bain",
        "d_totaal.real.p4_title": "Armoire sur mesure",
        "d_totaal.real.p4_cat": "Sur mesure",
        "d_totaal.real.cta": "Voir toutes les réalisations",
        "d_totaal.cta.title": "Un projet complet en tête ?",
        "d_totaal.cta.text": "Parlez-nous de vos plans. Nous les concrétisons ensemble.",
        "d_totaal.cta.btn": "Nous contacter",
        // diensten-keukens
        "title.d_keukens": "Cuisines sur mesure | Urban Interiors",
        "d_keukens.hero.label": "Service 04 — Cuisines",
        "d_keukens.hero.title": "Des cuisines<br><em class=\"text-italic\">où il fait bon vivre</em>",
        "d_keukens.hero.subtitle": "Des cuisines fonctionnelles sur mesure, pensées pour l'ergonomie, le détail et des matériaux durables. Le cœur battant de votre maison.",
        "d_keukens.hero.cta1": "Planifier un entretien",
        "d_keukens.hero.cta2": "Voir les réalisations",
        "d_keukens.aanpak.label": "Notre approche",
        "d_keukens.aanpak.title": "Pensée dans le moindre détail",
        "d_keukens.aanpak.text": "Une cuisine doit fonctionner comme vous cuisinez et vivez. Nous partons de vos habitudes pour les traduire en un design ergonomique et intemporel.",
        "d_keukens.aanpak.b1": "✔ Conception ergonomique sur mesure",
        "d_keukens.aanpak.b2": "✔ Plans de travail et matériaux haut de gamme",
        "d_keukens.aanpak.b3": "✔ Appareils et éclairage intégrés",
        "d_keukens.aanpak.b4": "✔ Finition épurée et sans joints apparents",
        "d_keukens.aanpak.text2": "Du classique chaleureux au noir épuré, nous construisons la cuisine qui vous ressemble.",
        "d_keukens.real.label": "Réalisations",
        "d_keukens.real.title": "Des cuisines que nous avons réalisées",
        "d_keukens.real.p1_title": "Cuisine épurée",
        "d_keukens.real.p1_cat": "Cuisines",
        "d_keukens.real.p2_title": "Cuisine design",
        "d_keukens.real.p2_cat": "Cuisines",
        "d_keukens.real.p3_title": "Cuisine noire",
        "d_keukens.real.p3_cat": "Cuisines",
        "d_keukens.real.p4_title": "Cuisine moderne",
        "d_keukens.real.p4_cat": "Cuisines",
        "d_keukens.real.cta": "Voir toutes les réalisations",
        "d_keukens.cta.title": "Vous rêvez d'une nouvelle cuisine ?",
        "d_keukens.cta.text": "Parlez-nous de vos envies. Nous réfléchissons avec vous, sans engagement.",
        "d_keukens.cta.btn": "Nous contacter",
        // diensten-badkamers
        "title.d_badkamers": "Salles de bain sur mesure | Urban Interiors",
        "d_badkamers.hero.label": "Service 05 — Salles de bain",
        "d_badkamers.hero.title": "Des salles de bain<br><em class=\"text-italic\">tout en sérénité</em>",
        "d_badkamers.hero.subtitle": "Une salle de bain pensée pour l'ambiance, la fonctionnalité et la durabilité. Votre lieu pour commencer et clôturer la journée.",
        "d_badkamers.hero.cta1": "Planifier un entretien",
        "d_badkamers.hero.cta2": "Voir les réalisations",
        "d_badkamers.aanpak.label": "Notre approche",
        "d_badkamers.aanpak.title": "Ambiance, fonction et durabilité",
        "d_badkamers.aanpak.text": "Nous concevons votre salle de bain autour du confort et de l'expérience, avec des matériaux qui résistent à l'humidité et au temps.",
        "d_badkamers.aanpak.b1": "✔ Agencement adapté à votre espace",
        "d_badkamers.aanpak.b2": "✔ Matériaux durables et résistants à l'humidité",
        "d_badkamers.aanpak.b3": "✔ Éclairage d'ambiance et mobilier sur mesure",
        "d_badkamers.aanpak.b4": "✔ Finition épurée et facile d'entretien",
        "d_badkamers.aanpak.text2": "De la salle d'eau compacte au vaste espace bien-être, tout est travaillé dans le détail.",
        "d_badkamers.real.label": "Réalisations",
        "d_badkamers.real.title": "Salles de bain et finitions",
        "d_badkamers.real.p1_title": "Salle de bain moderne",
        "d_badkamers.real.p1_cat": "Salles de bain",
        "d_badkamers.real.p2_title": "Finition sur mesure",
        "d_badkamers.real.p2_cat": "Sur mesure",
        "d_badkamers.real.p3_title": "Détail intérieur",
        "d_badkamers.real.p3_cat": "Intérieur",
        "d_badkamers.real.p4_title": "Espace de vie",
        "d_badkamers.real.p4_cat": "Intérieur",
        "d_badkamers.real.cta": "Voir toutes les réalisations",
        "d_badkamers.cta.title": "Envie d'une nouvelle salle de bain ?",
        "d_badkamers.cta.text": "Parlez-nous de vos envies. Nous réfléchissons avec vous, sans engagement.",
        "d_badkamers.cta.btn": "Nous contacter",
        // diensten-schrijnwerk
        "title.d_schrijnwerk": "Menuiserie sur mesure | Urban Interiors",
        "d_schrijnwerk.hero.label": "Service 06 — Menuiserie",
        "d_schrijnwerk.hero.title": "Menuiserie<br><em class=\"text-italic\">l'artisanat du bois</em>",
        "d_schrijnwerk.hero.subtitle": "Armoires, portes et escaliers sur mesure, parfaitement finis. Des solutions intégrées qui complètent un espace.",
        "d_schrijnwerk.hero.cta1": "Planifier un entretien",
        "d_schrijnwerk.hero.cta2": "Voir les réalisations",
        "d_schrijnwerk.aanpak.label": "Notre approche",
        "d_schrijnwerk.aanpak.title": "Du sur-mesure au millimètre près",
        "d_schrijnwerk.aanpak.text": "Chaque pièce de menuiserie est conçue sur mesure et réalisée avec soin, dans des matériaux qui durent des années.",
        "d_schrijnwerk.aanpak.b1": "✔ Armoires sur mesure et dressings",
        "d_schrijnwerk.aanpak.b2": "✔ Portes intérieures et escaliers sur mesure",
        "d_schrijnwerk.aanpak.b3": "✔ Solutions intégrées et sans raccords visibles",
        "d_schrijnwerk.aanpak.b4": "✔ Matériaux durables et finition épurée",
        "d_schrijnwerk.aanpak.text2": "D'un placard encastré invisible à un escalier marquant, tout avec la même précision.",
        "d_schrijnwerk.real.label": "Réalisations",
        "d_schrijnwerk.real.title": "Des menuiseries que nous avons réalisées",
        "d_schrijnwerk.real.p1_title": "Armoire multiplex",
        "d_schrijnwerk.real.p1_cat": "Sur mesure",
        "d_schrijnwerk.real.p2_title": "Détail d'armoire",
        "d_schrijnwerk.real.p2_cat": "Sur mesure",
        "d_schrijnwerk.real.p3_title": "Armoire de combles",
        "d_schrijnwerk.real.p3_cat": "Sur mesure",
        "d_schrijnwerk.real.p4_title": "Bar sur mesure",
        "d_schrijnwerk.real.p4_cat": "Sur mesure",
        "d_schrijnwerk.real.cta": "Voir toutes les réalisations",
        "d_schrijnwerk.cta.title": "Une idée de sur-mesure ?",
        "d_schrijnwerk.cta.text": "Parlez-nous de vos envies. Nous réfléchissons avec vous, sans engagement.",
        "d_schrijnwerk.cta.btn": "Nous contacter",

        // Werkwijze page
        "werkwijze.header.label": "De l'id\u00e9e \u00e0 la r\u00e9alisation",
        "werkwijze.header.title": "Approche",
        "werkwijze.header.subtitle": "Un parcours clair en cinq \u00e9tapes. Pas de surprises, mais un r\u00e9sultat qui dure.",
        "werkwijze.step1.title": "Premi\u00e8re rencontre",
        "werkwijze.step1.desc": "Un entretien sans engagement chez vous. Nous \u00e9coutons ce que vous souhaitez et ce qui vous manque.",
        "werkwijze.step2.title": "Concept & plan",
        "werkwijze.step2.desc": "Nous traduisons la conversation en une proposition visuelle. L'espace pour le feedback est toujours inclus.",
        "werkwijze.step3.title": "Mat\u00e9riaux & devis",
        "werkwijze.step3.desc": "Visites de showrooms, \u00e9chantillons et un budget transparent. Vous d\u00e9cidez, nous conseillons.",
        "werkwijze.step4.title": "Ex\u00e9cution",
        "werkwijze.step4.desc": "Nous coordonnons tout. Un seul interlocuteur, des mises \u00e0 jour r\u00e9guli\u00e8res, z\u00e9ro souci.",
        "werkwijze.step5.title": "Livraison",
        "werkwijze.step5.desc": "Termin\u00e9 quand tout est parfait. Nous restons disponibles apr\u00e8s la remise des cl\u00e9s.",
        "werkwijze.g1.title": "Prix fixe",
        "werkwijze.g1.desc": "Apr\u00e8s approbation du devis, le prix ne change pas. Pas de surprises, pas de co\u00fbts cach\u00e9s. Ce que nous convenons, c'est ce que vous payez.",
        "werkwijze.g2.title": "Un seul interlocuteur",
        "werkwijze.g2.desc": "Vous travaillez toujours avec la m\u00eame personne. Un contact qui supervise l'ensemble du projet \u2014 de la premi\u00e8re esquisse \u00e0 la derni\u00e8re finition.",
        "werkwijze.g3.title": "Planning clair",
        "werkwijze.g3.desc": "Vous savez \u00e0 l'avance quand chaque phase commence et se termine. Pas de devinettes. Des mises \u00e0 jour r\u00e9guli\u00e8res vous tiennent inform\u00e9 \u00e0 chaque \u00e9tape.",
        "werkwijze.cta.title": "Pr\u00eat pour un premier entretien ?",
        "werkwijze.cta.text": "Parlez-nous de votre projet. Nous planifions une rencontre sans engagement.",
        "werkwijze.cta.btn1": "Nous contacter",
        "werkwijze.cta.btn2": "Voir les r\u00e9alisations",

        // Realisaties page
        "realisaties.header.label": "Portfolio",
        "realisaties.header.title": "R\u00e9alisations",
        "realisaties.header.subtitle": "Une s\u00e9lection de projets termin\u00e9s. Diff\u00e9rentes maisons, diff\u00e9rents styles. Une constante : l'attention aux finitions.",
        "realisaties.filter.all": "Tout",
        "realisaties.filter.keukens": "Cuisines",
        "realisaties.filter.badkamers": "Salles de bain",
        "realisaties.filter.maatkasten": "Rangements",
        "realisaties.filter.woonkamer": "S\u00e9jour",
        "realisaties.filter.commercieel": "Commercial",
        "realisaties.filter.buitenwerk": "Ext\u00e9rieur",
        "realisaties.stat.projects": "Projets r\u00e9alis\u00e9s",
        "realisaties.stat.years": "Ans d'exp\u00e9rience",
        "realisaties.stat.clients": "Clients satisfaits",
        "realisaties.stat.region": "Europe & Benelux",
        "realisaties.cta.title": "Votre projet dans cette liste ?",
        "realisaties.cta.text": "Dites-nous \u00e0 quoi vous pensez. Nous discutons des possibilit\u00e9s sans engagement.",
        "realisaties.cta.btn1": "Nous contacter",
        "realisaties.cta.btn2": "Nos services",

        // Over page
        "over.header.label": "Qui nous sommes",
        "over.header.title": "\u00c0 propos d'Urban Interiors",
        "over.header.subtitle": "Le calme dans l'espace, la logique dans la conception, la qualit\u00e9 dans l'ex\u00e9cution.",
        "over.vision.label": "Notre vision",
        "over.vision.title": "Le calme dans le design",
        "over.vision.text1": "Urban Interiors est n\u00e9 d'une conviction simple : un int\u00e9rieur doit fonctionner logiquement et \u00eatre beau.",
        "over.vision.text2": "Nous cherchons l'\u00e9quilibre. Cela demande de l'attention. Pour la fa\u00e7on dont vous vivez, bougez, existez. Pour des mat\u00e9riaux qui vieillissent avec gr\u00e2ce.",
        "over.stat.projects": "Projets",
        "over.stat.years": "Ans d'exp\u00e9rience",
        "over.stat.clients": "Clients satisfaits",
        "over.stat.region": "Europe & Benelux",
        "over.why.label": "Pourquoi nous",
        "over.why.title": "Jeune et dynamique",
        "over.why.text1": "Une entreprise jeune et dynamique avec une vaste exp\u00e9rience dans le secteur de la construction.",
        "over.why.text2": "Nous combinons des id\u00e9es fra\u00eeches avec un savoir-faire \u00e9prouv\u00e9. Attention personnelle et ex\u00e9cution professionnelle.",
        "over.cta.title": "Envie de faire connaissance ?",
        "over.cta.text": "Nous vous en dirons plus sur notre approche. Sans engagement.",
        "over.cta.btn1": "Nous contacter",
        "over.cta.btn2": "Voir les r\u00e9alisations",

        // Contact page
        "contact.header.label": "Parlons-en",
        "contact.header.title": "Contact",
        "contact.header.subtitle": "Parlez-nous de votre projet. Nous \u00e9coutons et r\u00e9fl\u00e9chissons avec vous, sans engagement.",
        "contact.form.title": "Envoyer un message",
        "contact.form.name": "Nom",
        "contact.form.name_ph": "Votre nom",
        "contact.form.email": "Adresse e-mail",
        "contact.form.email_ph": "nom@exemple.be",
        "contact.form.phone": "T\u00e9l\u00e9phone",
        "contact.form.phone_ph": "+32 ...",
        "contact.form.message": "Message",
        "contact.form.message_ph": "D\u00e9crivez bri\u00e8vement votre projet...",
        "contact.form.submit": "Envoyer le message",
        "contact.form.success": "Merci pour votre message ! Nous vous contacterons rapidement.",
        "contact.info.title": "Coordonn\u00e9es",
        "contact.info.phone_label": "T\u00e9l\u00e9phone",
        "contact.info.email_label": "E-mail",
        "contact.info.location_label": "Localisation",
        "contact.info.location_value": "Europe & Benelux",
        "contact.info.hours_label": "Heures d'ouverture",
        "contact.info.hours_value": "Lun \u2013 Ven : 9h00 \u2013 16h00",

        // Bedankt page
        "bedankt.label": "Message envoy\u00e9",
        "bedankt.title": "Merci pour votre message",
        "bedankt.text": "Nous avons bien re\u00e7u votre message et vous contacterons dans les plus brefs d\u00e9lais.",
        "bedankt.cta": "Retour \u00e0 l'accueil",

        // 404 page
        "error.label": "Erreur",
        "error.title": "Page non trouv\u00e9e",
        "error.subtitle": "La page que vous cherchez n'existe pas ou a \u00e9t\u00e9 d\u00e9plac\u00e9e.",
        "error.text": "Pas de souci, nous vous ramenons sur le bon chemin. D\u00e9couvrez nos services ou contactez-nous.",
        "error.btn_home": "Vers la page d'accueil",
        "error.btn_contact": "Nous contacter",
        "error.cta.title": "Vous cherchez quelque chose ?",
        "error.cta.text": "D\u00e9couvrez nos services ou consultez nos r\u00e9alisations.",
        "error.cta.btn1": "Nos services",
        "error.cta.btn2": "Voir les r\u00e9alisations"
    },

    en: {
        // Navigation
        "nav.diensten": "Services",
        "nav.werkwijze": "Approach",
        "nav.realisaties": "Projects",
        "nav.over": "About",
        "nav.contact": "Contact",

        // Footer
        "footer.tagline": "Stylish custom interiors, down to the last detail. From design to execution with attention to quality and finishing.",
        "footer.nav_title": "Navigation",
        "footer.contact_title": "Contact",
        "footer.phone_label": "Phone",
        "footer.email_label": "Email",
        "footer.hours_title": "Opening Hours",
        "footer.weekdays": "Monday - Friday",
        "footer.weekdays_value": "9:00 AM \u2013 4:00 PM",
        "footer.weekend": "Weekend",
        "footer.weekend_value": "By appointment",
        "footer.location_label": "Location",
        "footer.location_value": "Europe & Benelux",
        "footer.copyright": "\u00a9 2026 Urban Interiors. All rights reserved.",
        "footer.made_by": "Made by <a href=\"https://nebula-agency.be\" target=\"_blank\" rel=\"noopener noreferrer\">nebula-agency.be</a>",
        "footer.diensten": "Services",
        "footer.werkwijze": "Approach",
        "footer.realisaties": "Projects",
        "footer.over": "About us",
        "footer.contact": "Contact",

        // Page titles
        "title.home": "Urban Interiors | Custom Interiors",
        "title.diensten": "Services | Urban Interiors",
        "title.werkwijze": "Approach | Urban Interiors",
        "title.realisaties": "Portfolio | Urban Interiors",
        "title.over": "About | Urban Interiors",
        "title.contact": "Contact | Urban Interiors",
        "title.404": "404 | Urban Interiors",

        // Homepage
        "home.hero.label": "Interior & Renovation",
        "home.hero.title": "Your Project. Our Expertise.<br><em class=\"text-italic\">Perfectly Executed.</em>",
        "home.hero.subtitle": "Stylish custom interiors, down to the last detail. From design to execution with attention to quality and finishing.",
        "home.hero.cta1": "View projects",
        "home.hero.cta2": "Get in touch",
        "home.intro.label": "About us",
        "home.intro.text": "We deliver complete renovations, custom interiors and extensions with one clear mission: quality without compromise.",
        "home.intro.text2": "From private homes to hospitality, retail and commercial spaces \u2014 at home and abroad, we bring projects to life with craftsmanship, precision and a flawless finish.",
        "home.services.label": "Services",
        "home.services.title": "What we do",
        "home.services.s1": "Interior Design",
        "home.services.s2": "Renovation",
        "home.services.s3": "Turnkey Project",
        "home.services.s4": "Kitchens",
        "home.services.s5": "Bathrooms",
        "home.services.s6": "Woodwork",
        "home.services.cta": "View all services",
        "home.vision.label": "Our vision",
        "home.vision.title": "Calm in design",
        "home.vision.text1": "A good interior doesn't demand attention. It just works. Calm in the space, logic in the design, quality in the execution.",
        "home.vision.text2": "We believe the best results come from collaboration. You know your own life best. We know how to translate that into space.",
        "home.vision.cta": "More about us",
        "home.portfolio.label": "Portfolio",
        "home.portfolio.title": "Recent projects",
        "home.portfolio.p1_title": "Modern Kitchen",
        "home.portfolio.p1_cat": "Kitchens",
        "home.portfolio.p2_title": "Mancave",
        "home.portfolio.p2_cat": "Interior",
        "home.portfolio.p3_title": "Modern Bathroom",
        "home.portfolio.p3_cat": "Bathrooms",
        "home.portfolio.p4_title": "Bar",
        "home.portfolio.p4_cat": "Commercial",
        "home.portfolio.cta": "View all projects",
        "home.process.label": "Approach",
        "home.process.title": "A clear process",
        "home.process.text1": "From introduction to delivery in 5 clear steps. You always know what we're doing and when.",
        "home.process.text2": "No surprises, no ambiguity. One point of contact, fixed prices and regular updates.",
        "home.process.cta": "Discover our approach",
        "home.cta.title": "Ready to start?",
        "home.cta.text": "Tell us what you have in mind. We'll think along and make it concrete.",
        "home.cta.btn": "Get in touch",

        // Diensten page
        "diensten.header.label": "What we do",
        "diensten.header.title": "Our services",
        "diensten.header.subtitle": "From interior design to renovation. Every project with the same attention to detail.",
        "diensten.s1.title": "Interior Design",
        "diensten.s1.desc": "Based on your wishes, we create a concrete plan for layout, materials and custom cabinetry.",
        "diensten.s2.title": "Renovation",
        "diensten.s2.desc": "We coordinate the works, monitor the schedule and ensure technical follow-up.",
        "diensten.s3.title": "Turnkey Project",
        "diensten.s3.desc": "From design to the final finish. Key in hand, ready to live in.",
        "diensten.s4.title": "Kitchens",
        "diensten.s4.desc": "Functional kitchens with attention to detail, ergonomics and quality materials.",
        "diensten.s5.title": "Bathrooms",
        "diensten.s5.desc": "Bathrooms with attention to atmosphere, functionality and durability.",
        "diensten.s6.title": "Woodwork",
        "diensten.s6.desc": "Custom cabinets, doors and stairs. Craftsmanship in wood.",
        "diensten.split.label": "For whom",
        "diensten.split.title": "Individuals & businesses",
        "diensten.split.text": "We work for those who value quality. Who prefer to do something well rather than quickly.",
        "diensten.split.cta": "Get in touch",
        "diensten.cta.title": "A project in mind?",
        "diensten.cta.text": "Tell us what you're thinking. We listen and think along, no obligations.",
        "diensten.cta.btn": "Get in touch",

        // Service: Interior design
        "title.d_interieur": "Interior Design | Urban Interiors",
        "d_interieur.hero.label": "Service 01 — Interior Design",
        "d_interieur.hero.title": "Interior design<br><em class=\"text-italic\">tailored to your life</em>",
        "d_interieur.hero.subtitle": "From layout and material choices to custom cabinetry. We translate the way you live into an interior that feels right, calm and finished down to the detail.",
        "d_interieur.hero.cta1": "Plan a conversation",
        "d_interieur.hero.cta2": "View projects",
        "d_interieur.aanpak.label": "Our approach",
        "d_interieur.aanpak.title": "From wish to space",
        "d_interieur.aanpak.text": "A good interior starts with listening. We bring your wishes, your space and your budget together into one clear plan, and execute it without surprises.",
        "d_interieur.aanpak.b1": "✔ Personal design and layout plan",
        "d_interieur.aanpak.b2": "✔ Advice on materials, colours and lighting",
        "d_interieur.aanpak.b3": "✔ Custom cabinetry and integrated solutions",
        "d_interieur.aanpak.b4": "✔ One point of contact from design to delivery",
        "d_interieur.aanpak.text2": "The result is an interior that is not only beautiful, but works, day after day.",
        "d_interieur.real.label": "Projects",
        "d_interieur.real.title": "Interiors we delivered",
        "d_interieur.real.p1_title": "Living Room Design",
        "d_interieur.real.p1_cat": "Interior",
        "d_interieur.real.p2_title": "Mancave",
        "d_interieur.real.p2_cat": "Interior",
        "d_interieur.real.p3_title": "Office Design",
        "d_interieur.real.p3_cat": "Commercial",
        "d_interieur.real.p4_title": "Custom Bar",
        "d_interieur.real.p4_cat": "Interior",
        "d_interieur.real.cta": "View all projects",
        "d_interieur.cta.title": "Ready for your interior?",
        "d_interieur.cta.text": "Tell us what you're thinking. We listen and think along, no obligations.",
        "d_interieur.cta.btn": "Get in touch",
        // diensten-renovatie
        "title.d_renovatie": "Renovation | Urban Interiors",
        "d_renovatie.hero.label": "Service 02 — Renovation",
        "d_renovatie.hero.title": "Renovate<br><em class=\"text-italic\">without worries</em>",
        "d_renovatie.hero.subtitle": "We take your renovation fully in hand. One point of contact, a tight schedule and technical follow-up, from demolition to delivery.",
        "d_renovatie.hero.cta1": "Plan a conversation",
        "d_renovatie.hero.cta2": "View projects",
        "d_renovatie.aanpak.label": "Our approach",
        "d_renovatie.aanpak.title": "Full coordination from A to Z",
        "d_renovatie.aanpak.text": "Renovation takes vision, planning and expertise. We coordinate all the works, safeguard the schedule and budget, and keep you informed at every step.",
        "d_renovatie.aanpak.b1": "✔ One fixed point of contact",
        "d_renovatie.aanpak.b2": "✔ Full coordination of the works",
        "d_renovatie.aanpak.b3": "✔ Technical follow-up and quality control",
        "d_renovatie.aanpak.b4": "✔ Respect for schedule and budget",
        "d_renovatie.aanpak.text2": "You don't have to worry about a thing, we ensure a smooth execution and a flawless end result.",
        "d_renovatie.real.label": "Projects",
        "d_renovatie.real.title": "Renovations we delivered",
        "d_renovatie.real.p1_title": "Renovation Project",
        "d_renovatie.real.p1_cat": "Renovation",
        "d_renovatie.real.p2_title": "Exterior Structure",
        "d_renovatie.real.p2_cat": "Exterior",
        "d_renovatie.real.p3_title": "Hair Salon",
        "d_renovatie.real.p3_cat": "Commercial",
        "d_renovatie.real.p4_title": "Custom Finish",
        "d_renovatie.real.p4_cat": "Custom",
        "d_renovatie.real.cta": "View all projects",
        "d_renovatie.cta.title": "Renovation plans?",
        "d_renovatie.cta.text": "Tell us about your project. We'll think along, no obligations.",
        "d_renovatie.cta.btn": "Get in touch",
        // diensten-totaalproject
        "title.d_totaal": "Turnkey Project | Urban Interiors",
        "d_totaal.hero.label": "Service 03 — Turnkey Project",
        "d_totaal.hero.title": "Turnkey,<br><em class=\"text-italic\">ready to live in</em>",
        "d_totaal.hero.subtitle": "From first design to the final finish. We deliver your entire project, all you have to do is open the door.",
        "d_totaal.hero.cta1": "Plan a conversation",
        "d_totaal.hero.cta2": "View projects",
        "d_totaal.aanpak.label": "Our approach",
        "d_totaal.aanpak.title": "From design to delivery",
        "d_totaal.aanpak.text": "One partner for your whole project. We design, plan, coordinate and finish, with the same attention to every detail.",
        "d_totaal.aanpak.b1": "✔ Design and 3D visualisation",
        "d_totaal.aanpak.b2": "✔ Full coordination of all trades",
        "d_totaal.aanpak.b3": "✔ Custom work and finishing in-house",
        "d_totaal.aanpak.b4": "✔ Turnkey delivery",
        "d_totaal.aanpak.text2": "One point of contact, one schedule, one person responsible, for a result that is entirely right.",
        "d_totaal.real.label": "Projects",
        "d_totaal.real.title": "Turnkey projects we delivered",
        "d_totaal.real.p1_title": "Sleek Kitchen",
        "d_totaal.real.p1_cat": "Kitchens",
        "d_totaal.real.p2_title": "Living Room",
        "d_totaal.real.p2_cat": "Interior",
        "d_totaal.real.p3_title": "Modern Bathroom",
        "d_totaal.real.p3_cat": "Bathrooms",
        "d_totaal.real.p4_title": "Custom Cabinet",
        "d_totaal.real.p4_cat": "Custom",
        "d_totaal.real.cta": "View all projects",
        "d_totaal.cta.title": "A complete project in mind?",
        "d_totaal.cta.text": "Tell us your plans. We'll make them concrete together.",
        "d_totaal.cta.btn": "Get in touch",
        // diensten-keukens
        "title.d_keukens": "Custom Kitchens | Urban Interiors",
        "d_keukens.hero.label": "Service 04 — Kitchens",
        "d_keukens.hero.title": "Kitchens<br><em class=\"text-italic\">made for living</em>",
        "d_keukens.hero.subtitle": "Functional custom kitchens, designed for ergonomics, detail and durable materials. The beating heart of your home.",
        "d_keukens.hero.cta1": "Plan a conversation",
        "d_keukens.hero.cta2": "View projects",
        "d_keukens.aanpak.label": "Our approach",
        "d_keukens.aanpak.title": "Considered down to every detail",
        "d_keukens.aanpak.text": "A kitchen should work the way you cook and live. We start from your habits and translate them into an ergonomic, timeless design.",
        "d_keukens.aanpak.b1": "✔ Ergonomic custom design",
        "d_keukens.aanpak.b2": "✔ High-quality worktops and materials",
        "d_keukens.aanpak.b3": "✔ Integrated appliances and lighting",
        "d_keukens.aanpak.b4": "✔ Sleek, seamless finishing",
        "d_keukens.aanpak.text2": "From warm classic to sleek and black, we build the kitchen that suits you.",
        "d_keukens.real.label": "Projects",
        "d_keukens.real.title": "Kitchens we delivered",
        "d_keukens.real.p1_title": "Sleek Kitchen",
        "d_keukens.real.p1_cat": "Kitchens",
        "d_keukens.real.p2_title": "Design Kitchen",
        "d_keukens.real.p2_cat": "Kitchens",
        "d_keukens.real.p3_title": "Black Kitchen",
        "d_keukens.real.p3_cat": "Kitchens",
        "d_keukens.real.p4_title": "Modern Kitchen",
        "d_keukens.real.p4_cat": "Kitchens",
        "d_keukens.real.cta": "View all projects",
        "d_keukens.cta.title": "Dreaming of a new kitchen?",
        "d_keukens.cta.text": "Tell us your wishes. We'll think along, no obligations.",
        "d_keukens.cta.btn": "Get in touch",
        // diensten-badkamers
        "title.d_badkamers": "Custom Bathrooms | Urban Interiors",
        "d_badkamers.hero.label": "Service 05 — Bathrooms",
        "d_badkamers.hero.title": "Bathrooms<br><em class=\"text-italic\">with calm and character</em>",
        "d_badkamers.hero.subtitle": "A bathroom designed for atmosphere, function and durability. Your place to start and end the day.",
        "d_badkamers.hero.cta1": "Plan a conversation",
        "d_badkamers.hero.cta2": "View projects",
        "d_badkamers.aanpak.label": "Our approach",
        "d_badkamers.aanpak.title": "Atmosphere, function and durability",
        "d_badkamers.aanpak.text": "We design your bathroom around comfort and experience, with materials built to withstand moisture and time.",
        "d_badkamers.aanpak.b1": "✔ Layout tailored to your space",
        "d_badkamers.aanpak.b2": "✔ Durable, moisture-resistant materials",
        "d_badkamers.aanpak.b3": "✔ Ambient lighting and custom furniture",
        "d_badkamers.aanpak.b4": "✔ Sleek, low-maintenance finishing",
        "d_badkamers.aanpak.text2": "From a compact guest bathroom to a spacious wellness space, everything worked out in detail.",
        "d_badkamers.real.label": "Projects",
        "d_badkamers.real.title": "Bathrooms and finishing",
        "d_badkamers.real.p1_title": "Modern Bathroom",
        "d_badkamers.real.p1_cat": "Bathrooms",
        "d_badkamers.real.p2_title": "Custom Finish",
        "d_badkamers.real.p2_cat": "Custom",
        "d_badkamers.real.p3_title": "Interior Detail",
        "d_badkamers.real.p3_cat": "Interior",
        "d_badkamers.real.p4_title": "Living Space",
        "d_badkamers.real.p4_cat": "Interior",
        "d_badkamers.real.cta": "View all projects",
        "d_badkamers.cta.title": "Ready for a new bathroom?",
        "d_badkamers.cta.text": "Tell us your wishes. We'll think along, no obligations.",
        "d_badkamers.cta.btn": "Get in touch",
        // diensten-schrijnwerk
        "title.d_schrijnwerk": "Custom Joinery | Urban Interiors",
        "d_schrijnwerk.hero.label": "Service 06 — Joinery",
        "d_schrijnwerk.hero.title": "Joinery<br><em class=\"text-italic\">craftsmanship in wood</em>",
        "d_schrijnwerk.hero.subtitle": "Custom cabinets, doors and stairs, made to measure and perfectly finished. Integrated solutions that complete a space.",
        "d_schrijnwerk.hero.cta1": "Plan a conversation",
        "d_schrijnwerk.hero.cta2": "View projects",
        "d_schrijnwerk.aanpak.label": "Our approach",
        "d_schrijnwerk.aanpak.title": "Custom work to the millimetre",
        "d_schrijnwerk.aanpak.text": "Every piece of joinery is designed to measure and crafted with care, in materials that last for years.",
        "d_schrijnwerk.aanpak.b1": "✔ Custom cabinets and dressings",
        "d_schrijnwerk.aanpak.b2": "✔ Made-to-measure interior doors and stairs",
        "d_schrijnwerk.aanpak.b3": "✔ Integrated, seamless solutions",
        "d_schrijnwerk.aanpak.b4": "✔ Durable materials and sleek finishing",
        "d_schrijnwerk.aanpak.text2": "From an invisible built-in closet to a striking staircase, all with the same precision.",
        "d_schrijnwerk.real.label": "Projects",
        "d_schrijnwerk.real.title": "Joinery we delivered",
        "d_schrijnwerk.real.p1_title": "Multiplex Cabinet",
        "d_schrijnwerk.real.p1_cat": "Custom",
        "d_schrijnwerk.real.p2_title": "Cabinet Detail",
        "d_schrijnwerk.real.p2_cat": "Custom",
        "d_schrijnwerk.real.p3_title": "Attic Cabinet",
        "d_schrijnwerk.real.p3_cat": "Custom",
        "d_schrijnwerk.real.p4_title": "Custom Bar",
        "d_schrijnwerk.real.p4_cat": "Custom",
        "d_schrijnwerk.real.cta": "View all projects",
        "d_schrijnwerk.cta.title": "An idea for custom work?",
        "d_schrijnwerk.cta.text": "Tell us your wishes. We'll think along, no obligations.",
        "d_schrijnwerk.cta.btn": "Get in touch",

        // Werkwijze page
        "werkwijze.header.label": "From idea to realisation",
        "werkwijze.header.title": "Approach",
        "werkwijze.header.subtitle": "A clear process in five steps. No surprises, just a result that lasts.",
        "werkwijze.step1.title": "Introduction",
        "werkwijze.step1.desc": "A no-obligation conversation at your home. We listen to what you want and what you're missing.",
        "werkwijze.step2.title": "Concept & plan",
        "werkwijze.step2.desc": "We translate the conversation into a visual proposal. Room for feedback is always included.",
        "werkwijze.step3.title": "Materials & quote",
        "werkwijze.step3.desc": "Showroom visits, samples and a transparent budget. You decide, we advise.",
        "werkwijze.step4.title": "Execution",
        "werkwijze.step4.desc": "We coordinate everything. One point of contact, regular updates, no worries.",
        "werkwijze.step5.title": "Delivery",
        "werkwijze.step5.desc": "Done when everything is right. We remain available after the key handover.",
        "werkwijze.g1.title": "Fixed price",
        "werkwijze.g1.desc": "After approval of the quote, the price doesn't change. No surprises, no hidden costs. What we agree on is what you pay.",
        "werkwijze.g2.title": "One point of contact",
        "werkwijze.g2.desc": "You always work with the same person. One contact who oversees the entire project \u2014 from first sketch to final finish.",
        "werkwijze.g3.title": "Clear planning",
        "werkwijze.g3.desc": "You know in advance when each phase starts and ends. No guesswork. Regular updates keep you involved at every step.",
        "werkwijze.cta.title": "Ready for a first conversation?",
        "werkwijze.cta.text": "Tell us about your project. We'll schedule a no-obligation introduction.",
        "werkwijze.cta.btn1": "Get in touch",
        "werkwijze.cta.btn2": "View projects",

        // Realisaties page
        "realisaties.header.label": "Portfolio",
        "realisaties.header.title": "Projects",
        "realisaties.header.subtitle": "A selection of completed projects. Different homes, different styles. One constant: attention to finishing.",
        "realisaties.filter.all": "All",
        "realisaties.filter.keukens": "Kitchens",
        "realisaties.filter.badkamers": "Bathrooms",
        "realisaties.filter.maatkasten": "Custom Cabinets",
        "realisaties.filter.woonkamer": "Living Room",
        "realisaties.filter.commercieel": "Commercial",
        "realisaties.filter.buitenwerk": "Exterior",
        "realisaties.stat.projects": "Projects completed",
        "realisaties.stat.years": "Years of experience",
        "realisaties.stat.clients": "Satisfied clients",
        "realisaties.stat.region": "Europe & Benelux",
        "realisaties.cta.title": "Your project on this list?",
        "realisaties.cta.text": "Tell us what you're thinking. We'll discuss the possibilities, no obligations.",
        "realisaties.cta.btn1": "Get in touch",
        "realisaties.cta.btn2": "Our services",

        // Over page
        "over.header.label": "Who we are",
        "over.header.title": "About Urban Interiors",
        "over.header.subtitle": "Calm in the space, logic in the design, quality in the execution.",
        "over.vision.label": "Our vision",
        "over.vision.title": "Calm in design",
        "over.vision.text1": "Urban Interiors was born from a simple conviction: an interior must work logically and look beautiful.",
        "over.vision.text2": "We seek balance. That requires attention. To how you live, move, exist. To materials that age with grace.",
        "over.stat.projects": "Projects",
        "over.stat.years": "Years of experience",
        "over.stat.clients": "Satisfied clients",
        "over.stat.region": "Europe & Benelux",
        "over.why.label": "Why us",
        "over.why.title": "Young and dynamic",
        "over.why.text1": "A young, dynamic company with extensive experience in the construction sector.",
        "over.why.text2": "We combine fresh ideas with proven craftsmanship. Personal attention with professional execution.",
        "over.cta.title": "Want to get acquainted?",
        "over.cta.text": "We'd love to tell you more about our approach. No obligations.",
        "over.cta.btn1": "Get in touch",
        "over.cta.btn2": "View projects",

        // Contact page
        "contact.header.label": "Let's talk",
        "contact.header.title": "Contact",
        "contact.header.subtitle": "Tell us about your project. We listen and think along, no obligations.",
        "contact.form.title": "Send a message",
        "contact.form.name": "Name",
        "contact.form.name_ph": "Your name",
        "contact.form.email": "Email address",
        "contact.form.email_ph": "name@example.com",
        "contact.form.phone": "Phone",
        "contact.form.phone_ph": "+32 ...",
        "contact.form.message": "Message",
        "contact.form.message_ph": "Briefly tell us about your project...",
        "contact.form.submit": "Send message",
        "contact.form.success": "Thank you for your message! We'll get back to you soon.",
        "contact.info.title": "Contact details",
        "contact.info.phone_label": "Phone",
        "contact.info.email_label": "Email",
        "contact.info.location_label": "Location",
        "contact.info.location_value": "Europe & Benelux",
        "contact.info.hours_label": "Opening hours",
        "contact.info.hours_value": "Mon \u2013 Fri: 9:00 AM \u2013 4:00 PM",

        // Bedankt page
        "bedankt.label": "Message sent",
        "bedankt.title": "Thank you for your message",
        "bedankt.text": "We have received your message and will get back to you as soon as possible.",
        "bedankt.cta": "Back to home",

        // 404 page
        "error.label": "Error",
        "error.title": "Page not found",
        "error.subtitle": "The page you're looking for doesn't exist or has been moved.",
        "error.text": "No worries, we'll get you back on track. Explore our services or get in touch with us.",
        "error.btn_home": "Go to homepage",
        "error.btn_contact": "Get in touch",
        "error.cta.title": "Looking for something?",
        "error.cta.text": "Discover our services or browse our projects.",
        "error.cta.btn1": "Our services",
        "error.cta.btn2": "View projects"
    }
};

// Apply translations
function setLanguage(lang) {
    if (!translations[lang]) return;
    localStorage.setItem('ui-lang', lang);
    document.documentElement.lang = lang;

    // Update text content
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        const val = translations[lang][key];
        if (val !== undefined) {
            if (el.hasAttribute('data-i18n-html')) {
                el.innerHTML = val;
            } else {
                el.textContent = val;
            }
        }
    });

    // Update placeholders
    document.querySelectorAll('[data-i18n-ph]').forEach(el => {
        const key = el.getAttribute('data-i18n-ph');
        const val = translations[lang][key];
        if (val !== undefined) {
            el.placeholder = val;
        }
    });

    // Update page title
    const path = window.location.pathname.replace(/\/$/, '').split('/').pop() || 'index';
    const pageMap = { 'index': 'home', 'index.html': 'home', 'diensten': 'diensten', 'diensten.html': 'diensten', 'werkwijze': 'werkwijze', 'werkwijze.html': 'werkwijze', 'realisaties': 'realisaties', 'realisaties.html': 'realisaties', 'over': 'over', 'over.html': 'over', 'contact': 'contact', 'contact.html': 'contact', '404': '404', '404.html': '404', 'diensten-interieurinrichting': 'd_interieur', 'diensten-interieurinrichting.html': 'd_interieur', 'diensten-renovatie': 'd_renovatie', 'diensten-renovatie.html': 'd_renovatie', 'diensten-totaalproject': 'd_totaal', 'diensten-totaalproject.html': 'd_totaal', 'diensten-keukens': 'd_keukens', 'diensten-keukens.html': 'd_keukens', 'diensten-badkamers': 'd_badkamers', 'diensten-badkamers.html': 'd_badkamers', 'diensten-schrijnwerk': 'd_schrijnwerk', 'diensten-schrijnwerk.html': 'd_schrijnwerk' };
    const titleKey = 'title.' + (pageMap[path] || 'home');
    if (translations[lang][titleKey]) {
        document.title = translations[lang][titleKey];
    }

    // Update lang switcher active state
    document.querySelectorAll('.lang-option').forEach(btn => {
        btn.classList.toggle('active', btn.dataset.lang === lang);
    });
}

// Initialize
document.addEventListener('DOMContentLoaded', () => {
    const saved = localStorage.getItem('ui-lang') || 'nl';
    setLanguage(saved);

    // Bind lang switcher clicks
    document.querySelectorAll('.lang-option').forEach(btn => {
        btn.addEventListener('click', (e) => {
            e.preventDefault();
            setLanguage(btn.dataset.lang);
        });
    });
});
